- 
  branches:
    only:
      - master
      - develop
      
  clone_folder: c:\work\alphacloud.msbuild.xslt.nuget
  
  pull_requests:
    do_not_increment_build_number: true

  os: Visual Studio 2015

  nuget:
    disable_publish_on_pr: true

  assembly_info:
    patch: false
  
  cache:
    - src\packages -> src\**\packages.config

  install:
    - choco install gitversion.portable -y

  before_build:
    - nuget restore
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo
    
  build_script:
  - cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" build.proj /t:BuildAll /p:PackageVersion="%GitVersion_NuGetVersion%'

  test:
    assemblies:
    - src\tests\bin\Release\Alphacloud.MSBuild.Xslt.Tests.dll 

  artifacts:
  - path: out/packages/*.nupkg
    name: Nuget packages

  deploy:
  - provider: NuGet
    api_key:
      secure: yHJuxI0TVZU+g90YoGwOm8Zug7bxKNibC84NLkLusrMMNMcR86qizmvJR81KHtCS


-      
  clone_folder: c:\work\alphacloud.msbuild.xslt.dev
  
  pull_requests:
    do_not_increment_build_number: true

  os: Visual Studio 2015

  nuget:
    disable_publish_on_pr: true

  assembly_info:
    patch: false
  
  cache:
    - src\packages -> src\**\packages.config

  install:
    - choco install gitversion.portable -y

  before_build:
    - nuget restore
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo
    
  build_script:
  - cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" build.proj /t:BuildAll'

  test:
    assemblies:
    - src\tests\bin\Release\Alphacloud.MSBuild.Xslt.Tests.dll 
