version: 0.2.2-beta-{build}

pull_requests:

  do_not_increment_build_number: true

os: Visual Studio 2015

nuget:

  disable_publish_on_pr: true

build_script:

- cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" build.proj'

test:

  assemblies:

  - src\tests\bin\Release\Alphacloud.MSBuild.Xslt.Tests.dll 

artifacts:

- path: out/packages/*.nupkg

  name: Nuget packages

deploy:

- provider: NuGet

  api_key:

    secure: yHJuxI0TVZU+g90YoGwOm8Zug7bxKNibC84NLkLusrMMNMcR86qizmvJR81KHtCS

  on:

    branch: master