- 
  branches:
    only:
      - master
      - develop
      
  skip_tags: true

  pull_requests:
    do_not_increment_build_number: true

  os: Visual Studio 2015

  nuget:
    disable_publish_on_pr: true

  assembly_info:
    patch: false

  environment:
    CHOCOLATEY_KEY:
      secure: 9M5HbeG8Cc5XbyirU+F+mVmtVP1tJ9WB8n4s3ATg+doSkUNODnFZ0LAdR44o2Jcd
    NUGET_KEY:
      secure: yDtlwZxOr+meDM0iMA3pWo3VO+t2oRDIjf+accbVz3N2NO74W6yhF7lgRjw9B2Ek
    
  install:
    - choco install gitversion.portable -pre -y

  before_build:
    - ps: C:\ProgramData\chocolatey\bin\gfv.exe /l console /output buildserver /updateAssemblyInfo
    - ps: appveyor-retry nuget restore src\Alphacloud.MSBuild.Xslt.sln 
    
  build_script:
  - cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" build.proj /t:BuildAll;Pack /p:PackageVersion="%GitVersion_NuGetVersion%'

  test:
    assemblies:
    - src\tests\bin\Release\Alphacloud.MSBuild.Xslt.Tests.dll 

  artifacts:
  - path: out/packages/*.nupkg

  deploy_script:
  - ps: >-
      $version = $env:GitVersion_NuGetVersion ;
      nuget setApiKey $env:NUGET_KEY -verbosity quiet;
      appveyor-retry nuget push out\packages\Alphacloud.MSBuild.Xslt.$version.nupkg -source https://www.nuget.org/api/v2/package/ ;
      cd src\solution ;
      choco pack xslt.portable.nuspec --version $version ;
      if ($env:APPVEYOR_REPO_BRANCH -eq 'master') {
        choco apiKey -k $env:CHOCOLATEY_KEY -source https://chocolatey.org/ ;
        appveyor-retry choco push msbuild-xslt.portable.$version.nupkg
      }
      
-      
  pull_requests:
    do_not_increment_build_number: true

  os: Visual Studio 2015

  nuget:
    disable_publish_on_pr: true

  assembly_info:
    patch: false
  
  cache:
    - packages -> src\**\packages.config

  install:
    - choco install gitversion.portable -pre -y

  before_build:
    - ps: gitversion /l console /output buildserver /updateAssemblyInfo
    
  build_script:
  - cmd: '"%ProgramFiles(x86)%\MSBuild\14.0\Bin\MSBuild.exe" build.proj /t:BuildAll'

  test:
    assemblies:
    - src\tests\bin\Release\Alphacloud.MSBuild.Xslt.Tests.dll 
